# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ShowPlotWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_plot_show(object):
    def setupUi(self, Form_plot_show):
        Form_plot_show.setObjectName("Form_plot_show")
        Form_plot_show.resize(473, 380)
        Form_plot_show.setStyleSheet("background-color: rgb(177, 177, 177);")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form_plot_show)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(130, 90, 160, 89))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = PlotWidget(self.verticalLayoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)

        self.retranslateUi(Form_plot_show)
        QtCore.QMetaObject.connectSlotsByName(Form_plot_show)

    def retranslateUi(self, Form_plot_show):
        _translate = QtCore.QCoreApplication.translate
        Form_plot_show.setWindowTitle(_translate("Form_plot_show", "Form"))
from pyqtgraph import PlotWidget
